project_id = "cwwkkhcpbswvwghxbfgg"

[functions.printavo-sync]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-mockup-email]
verify_jwt = false

[functions.shopify-sync]
verify_jwt = false

[functions.notify-customer]
verify_jwt = false

[functions.ss-activewear-api]
verify_jwt = false

[functions.printavo-customer-sync]
verify_jwt = false

[functions.create-quote-action-item]
verify_jwt = false

[functions.push-to-printavo]
verify_jwt = false

[functions.quote-follow-up]
verify_jwt = false
